replicaCount: 1

image:
  repository: buildkite/agent
  # Note that by default we use appVersion to get image tag version
  # tag:
  pullPolicy: IfNotPresent

agent:
  tags: "role=agent"
  externalSecretName: "buildkite-agent"
  externalSecretTokenKey: "token"

enableHostDocker: false

dind:
  enabled: true
